### ISSUE TITLE
Add Authorization Piece

### ISSUE THREAD

**Issue by dancingshell** [eardish/ephect-dataobjects#22]
Add logic to db-orm that looks at the request and decides if the current user has privileges to perform given request

ex- to update group profile, we need to validate that the current user is a member of the group or has admin privileges in the user_group table

**Comment by robinagist** [comment]
made a change to the <code>ControllerInterface</code>.  added a <code>'hasPermission()'</code> method that returns a true or false, depending on whether or not a user has permission to perform an action.  All controller interfaces that implement <code>ControllerInterface</code> will need to add the <code>hasPermission()</code> method.

**Comment by robinagist** [comment]
slight change:  instead of imposing a <code>hasPermission()</code> on each Controller by putting it on the <code>ControllerInterface</code> , I decided to use a mix-in (in this case, a PHP Trait).  This will allow any controller that needs an ACL'd permission system to simply extend the trait.

**Comment by JordanRL** [comment]
Please don't use the term mixin :P 

Also, I thought we weren't doing an ACL system? We're just hardcoding an acceptance for this particular user right now?

**Comment by robinagist** [comment]
most definitely not a full ACL system.  but it uses an ACL like mechanism.  won't be fully flushed out, but it does use a bitmask and some bit operations.

**Comment by robinagist** [comment]
a comment for me to reference later:

define( "INCLUDE_HIDDEN", 0x1 );
define( "HIDE_EXTS", 0x2 );
define( "SHOW_ABSOLUTE_PATHS", 0x4 );
//And so on, 0x8, 0x10, 0x20, 0x40, 0x80, 0x100, 0x200, 0x400, 0x800 etc..
You can then check for individual flags in your ls function:

if( $flags & INCLUDE_HIDDEN ) { //<-- note just a single &, bitwise and
    //$flags have INCLUDE_HIDDEN
}

**Comment by robinagist** [comment]
the solution is a simple Trait called <code>Perms</code> that is <code>use></code>d by the Controller and has a single method, <code>hasPermissions()</code> that is called in beginning of the desired controller action.  A bitmask containing the required permissions flag is passed in with the user's setting in that context.  if any single flag required is not set, it immediately fails and returns false.
